### ISSUE TITLE
#Backend

### ISSUE THREAD

**Issue by JeremasPosta** [JeremasPosta/autodidapptas#1]
Decidir Si vamos a usar un Framework o PHP crudo.

**Comment by elendex** [comment]
Si es por mi usaría PHP crudo. Pero lo mas acorde seria usar un Framework ya que va a ser lo mas cercano a como se trabaja actualmente.

Personalmente trabajaría usando Laravel.

**Comment by JeremasPosta** [comment]
Me parece bien. Te animas a subir el boilerplate del proyecto?

**Comment by JeremasPosta** [comment]
Me parece bien. Te animas a subir el boilerplate del proyecto?

**Comment by elendex** [comment]
Perdón, que sería el boilerplate?

**Comment by JeremasPosta** [comment]
Boilerplate es el "esqueleto" lo que te crea el framework cuando arrancás
un proyecto nuevo.

**Comment by elendex** [comment]
Ahhh listo, si, dale, me viene bien para practicar. Me encargo entonces.

**Comment by elendex** [comment]
No se si está bien pero traté de crear una rama llamada 'Laravel_Test' para ir probando trabajar con este framework.

**Comment by JeremasPosta** [comment]
Yo lo veo muy bien! 
Estuvo bien mantener el `index` original.

Te pregunto porque no entiendo bien el manejo de assets del framework, el index original usa las hojas de estilos, esto se sigue manteniendo sin cambios?

**Comment by elendex** [comment]
Ahora los archivos css tienen que guardarse en la carpeta public/css/ y hay que enlazarlos usando esa función asset() que apunta a esa carpeta public. También se puede escribir toda la ruta...creo. Pero si se usan las llaves {{ }} ese archivo css lo compila una vez y no cada vez que se ejecuta la aplicación, algo así. Voy aprendiendo sobre la marcha.

**Comment by JeremasPosta** [comment]
Genial, sí, ahí los ví. Debería funcionar. Imagino que tuviste que crear un archivo `.env` con las credenciales y lo tenés en local. Si hay alguna consideración respecto a eso, te la dejo encargada.

Te pido si podés completar el Readme con los requisitos básicos de esto, (Que base de datos configuraste, versión, versión de PHP, versión de Laravel). 

Una vez que esté eso, te invito a hacer el pull request de tu rama hacia Main. Todo se ve bien. 👍

**Comment by elendex** [comment]
Yo acá en local tengo instalado el xampp, que es el que vengo usando acá y en mi laburo, y para practicar Laravel me instalé el Laragon. Una vez que cloné el repositorio lo levante en xampp y todo bien, y después en Laragon se veia igual. Hice esto para ver si había colocado bien los archivos, tanto el index como los css. Lo que quiero decir es que lo probé que levantara bien lo que se había echo. 

El archivo .env por ahora no lo modifiqué. Lo próximo seria crear la BD, y ahí si tengo que cambiar algo del .env. Pero dale, dejame revisar mejor esa parte. 

Voy completando el Readme dale.
